task_manager_app/urls.py
# task_manager_app/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),
]

tasks/urls.py
"""
Defines the URL patterns for the task manager application.
It maps URL paths to the corresponding view functions,
enabling navigation and interaction within the application.
"""
# tasks/urls.py
from django.urls import path
from . import views

# Namespacing URL names
app_name = "tasks"  # Set the application namespace
urlpatterns = [
    path('', views.index, name='index'),
    path('task/view/<int:task_id>/', views.view_task, name='view_task'),
    path('task/edit/<int:task_id>/', views.edit_task, name='edit_task'),
    path('task/delete/<int:task_id>/', views.delete_task, name='delete_task'),
]

tasks/models.py
"""
Defines the database models for the task manager application.
It includes the Task model, which represents a task with fields
for title, description, category, deadline, and priority
"""
# tasks/models.py

from django.db import models
from django.core.exceptions import ValidationError
from django.utils import timezone


def validate_deadline_date(date) -> None:
    """Checks if the date entered is in the past. If so,
    raise a ValidationError"""

    if date < timezone.now().date():
        raise ValidationError("Oops🤔. The deadline date cannot be "
                              "in the past."
                              )


PRIORITY_CHOICES = [  # Choices for the priority level field
    (1, 'High'),
    (2, 'Medium'),
    (3, 'Low'),
]


# Create your models here.
class Task(models.Model):
    """A subclass representing a task"""

    title = models.CharField(max_length=50)
    description = models.TextField()
    category = models.CharField(max_length=30)
    # Represented in Python by a datetime.date instance
    deadline = models.DateField(validators=[validate_deadline_date])
    priority = models.IntegerField(
        choices=PRIORITY_CHOICES,
        default=PRIORITY_CHOICES[2],
        )

    # def get_absolute_url(self):
    #     """Docstring"""
    #     return reverse('view_task', args=[str(self.id)])

    def __str__(self) -> str:
        """Returns the task title as a string"""

        return f'{self.title}'

tasks/forms.py
"""
Defines the form for the task manager application.
It includes the TaskForm, which handles user input for
creating and updating tasks

Note: There is no need to define the field types as they have already
been defined in the model
"""
# tasks/forms.py

from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    """
    A form for creating and updating Task instances

    Creates a Form class from a Django model. It will have a form field
    for every model field specified. The label used comes from the model
    """

    class Meta:
        """Defines the metadata options for the TaskForm"""
        model = Task
        # Include all the other fields apart from the id
        exclude = ['id']
        widgets = {
            # Deadline field should use a HTML5 date input
            'deadline': forms.DateInput(
                attrs={'type': 'date'}
            ),
            'title': forms.TextInput(
                attrs={'placeholder': "Grocery Shopping"}
            ),
            'description': forms.Textarea(
                attrs={'placeholder': "Purchase items from the grocery "
                       "list including fruits, vegetables, and "
                       "household essentials."}
            ),
            'category': forms.TextInput(
                attrs={'placeholder': 'Shopping'}
            ),
        }
        help_texts = {
            'deadline': 'Please ensure that deadline starts from today'
        }
        # Labels could be set here to

    def save(self, commit=True):
        """
        Overrides the save behaviour of the form to modify the
        category and title value before saving it to the database

        The commit parameter determines whether the changes are saved to
        the database immediately (True by default)
        """
        # Calls 'ModelForm' save method, which creates a model instance
        # but does not save it to the database yet
        instance = super(TaskForm, self).save(commit=False)

        if instance.title:  # Checks if it has a value
            instance.title = instance.title.title()

        if instance.category:
            instance.category = instance.category.title()

        # Save the instance to the database if commit is True
        if commit:
            instance.save()

        return instance

tasks/views.py
"""
Defines the view functions for the task manager application.
It handles HTTP requests and returns appropriate HTTP responses,
rendering templates and performing CRUD operations on the Task model.
"""
# tasks/views.py
from django.http import HttpResponse, HttpResponseRedirect, HttpRequest
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from django.utils import timezone
import pytz
from .models import Task
from .forms import TaskForm


# Create your views here.
def index(request: HttpRequest) -> HttpResponse | HttpResponseRedirect:
    """
    Retrieves the id, title, and description of:

    1. All tasks
    2. All tasks that are due today
    3. All tasks that have passed their deadline date

    from the database and renders the index template

    Parameters
    ----------
    request: HttpRequest
        Contains metadata about the request

    Returns
    ----------
    HttpResponse | HttpResponseRedirect
    """

    # Get results as namedtuple()
    tasks = (Task.objects.
             order_by("title").
             values_list("id", "title", "description", named=True
                         )
             )

    now_utc = timezone.now()  # Get current time in UTC
    london_timezone = pytz.timezone('Europe/London')
    # Convert current time to London time zone as UTC is 1 hour behind
    now_london = now_utc.astimezone(london_timezone).date()

    tasks_due_today = (  # Get tasks
        Task.objects.
        order_by("title").
        filter(deadline=now_london).
        values_list("id", "title", "description", named=True
                    )
        )

    tasks_passed_deadline = (
        Task.objects.
        order_by("deadline").
        filter(deadline__lt=now_london).
        values_list("id", "title", "description", named=True
                    )
        )

    # Check if form has been submitted and save task (if valid)
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            messages.success(request, 'Task was created successfully')
            form.save()
            return redirect('tasks:index')
    else:
        form = TaskForm()  # Display task form

    context = {
        'tasks': tasks,
        'tasks_due_today': tasks_due_today,
        'tasks_passed_deadline': tasks_passed_deadline,
        'form': form,
    }

    return render(request, 'index.html', context=context)


def view_task(request: HttpRequest, task_id: int) -> HttpResponse:
    """
    It retrieves the id, title, and description of:

    1. Tasks with the same deadline as the task_id
    2. Tasks with the same category as the task_id
    3. Tasks with the same priority as the task_id

    from the database and then renders the view_task template

    Parameters
    ----------
    request: HttpRequest
        Contains metadata about the request
    task_id: int
        Represents the id of the task

    Returns
    ----------
    HttpResponse | HttpResponseRedirect
    """

    # If task does not exist, raise an error
    task = get_object_or_404(Task, id=task_id)

    # Get tasks that are related to the current task
    # Randomise the order of the QuerySet
    tasks_with_same_deadline = (
        Task.objects.
        filter(deadline=task.deadline).
        exclude(id=task.id).
        order_by("?").
        values_list("id", "title", "description", named=True
                    )[:4]
        )

    tasks_with_same_category = (
        Task.objects.
        filter(category=task.category).
        exclude(id=task.id).
        order_by("?").
        values_list("id", "title", "description", named=True
                    )[:4]
        )

    tasks_with_same_priority = (
        Task.objects.
        filter(priority=task.priority).
        exclude(id=task.id).
        order_by("?").
        values_list("id", "title", "description", named=True
                    )[:4]
        )

    context = {
        'task': task,
        'tasks_with_same_deadline': tasks_with_same_deadline,
        'tasks_with_same_category': tasks_with_same_category,
        'tasks_with_same_priority': tasks_with_same_priority,
    }

    return render(request, 'view_task.html', context=context)


def edit_task(request: HttpRequest,
              task_id: int) -> HttpResponse | HttpResponseRedirect:
    """
    It retrieves a task from the database and renders the edit_task
    page

    Parameters
    ----------
    request: HttpRequest
        Contains metadata about the request
    task_id: int
        Represents the id of the task

    Returns
    ----------
    HttpResponse | HttpResponseRedirect
    """

    task = get_object_or_404(Task, id=task_id)

    if request.method == 'POST':
        # Create a TaskForm instance with submitted data, and bind it
        # to the existing task instance
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            if form.has_changed():
                messages.success(request, 'Task was updated successfully')
                form.save()
            return redirect('tasks:view_task', task_id=task.id)
    else:
        # Creates a TaskForm instance pre-filled with the current task
        # data if form is being accessed for the first time
        form = TaskForm(instance=task)

    context = {
        'form': form,
        'task': task,
    }

    return render(request, 'edit_task.html', context=context)


@require_POST  # Deletion should be done via a POST request
def delete_task(request: HttpRequest,
                task_id: int) -> HttpResponseRedirect:
    """
    Retrieves a task from the database and deletes it.

    Parameters
    ----------
    request: HttpRequest
        Contains metadata about the request
    task_id: int
        Represents the id of the task

    Returns
    ----------
    HttpResponse | HttpResponseRedirect
    """

    task = get_object_or_404(Task, id=task_id)
    task.delete()
    messages.success(request, 'Task was deleted successfully')
    return redirect('tasks:index')

tasks/templates/base.html
<!-- tasks/templates/base.html -->
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Task manager application" />
    <meta name="author" content="Andy" />
    <!-- Icon library - Font Awesome 6 through cdnjs -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <!-- Google font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Acme&display=swap" rel="stylesheet">
    <!-- Stylesheet -->
    <link rel="stylesheet" href="{% static 'styles.css' %}" />
    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body class="acme-regular">
    {% include 'partials/header.html' %}
    <main>{% block content %}{% endblock content %}</main>
    {% include 'partials/footer.html' %}
  </body>
</html>

tasks/templates/edit_task.html
<!-- tasks/templates/edit_task.html -->
{% extends 'base.html' %} 
{% load static %}

{% block title %}Edit task{% endblock title %} 

{% block content %}
<section class="edit-form-section-container">
    <div class="edit-form-header-container">
        <h2 class="edit-task-heading">Edit task</h2>
        <a 
            href="{% url 'tasks:view_task' task.id %}"
            class="edit-go-back-to-tasks-link">Go back to task
        </a>
    </div>
    <div class="edit-form-container">
        <div class="edit-form-div">
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button 
                    type="submit"
                    class="create-task-button">Save changes
                </button>
            </form>
        </div>
        <div class="img-container">
            <img 
                src="{% static '../static/images/sticky-notes-img.jpg' %}"
                alt="sticky notes"
                class="img" />
        </div>
    </div>
</section>
{% endblock content %}

tasks/templates/index.html
<!-- tasks/templates/index.html -->
{% extends 'base.html' %}
{% load icons %}

{% block title %}Home Page{% endblock title %}

{% block content %}
{% if not tasks %}
  <div class="no-tasks-div">
    <h2 class="no-tasks-heading">No tasks. Get started below!</h2>
  </div>
{% else %}
  <div class="message-div">
    {% if messages %}
      {% for message in messages %}
        <div class="{{ message.tags }}">
          {{ message }}
          <!-- Generates <i class="fa-solid fa-circle-check"></i> -->
          {% icon 'circle-check' %}
        </div>
      {% endfor %}
    {% endif %}
  </div>
  <div class="number-of-tasks-div">
    <h2>You have {{ tasks|length}} task{{tasks|pluralize}}</h2>
    <div class="tasks-container">
      <section class="main-tasks-section">
        <table class="main-tasks-table">
          <caption>
            Your tasks
          </caption>
          <thead>
            <tr>
              <th scope="col">Title</th>
              <th scope="col">Description</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            {% for task in tasks %}
              <tr>
                <td>{{ task.title|capfirst }}</td>
                <td>{{ task.description|truncatechars:20 }}</td>
                <td>
                  <a href="{% url 'tasks:view_task' task.id %}">View task<a>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </section>
      <section class="other-info-section">
        <aside class="sticky-container">
          <div class="sticky-div">
            {% if not tasks_due_today %}
              <h2 class="stick-div-no-tasks-heading">No tasks due today</h2>
              {% else %}
              <table class="sticky-tasks-table">
                <caption class="sticky-table-caption">
                  Tasks Due Today
                </caption>
                <thead>
                  <tr>
                    <th scope="col">Title</th>
                    <th scope="col">Description</th>
                    <th scope="col"></th>
                  </tr>
                </thead>
                <tbody>
                  {% for task in tasks_due_today %}
                    <tr>
                      <td>{{ task.title|capfirst }}</td>
                      <td>{{ task.description|truncatechars:15 }}</td>
                      <td>
                        <a href="{% url 'tasks:view_task' task.id %}">View task
                        </a>
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            {% endif %}
          </div>
          <div class="sticky-div passed-deadline-div">
            {% if not tasks_passed_deadline %}
              <h2 class="stick-div-no-tasks-heading">No tasks passed deadline
              </h2>
            {% else %}
              <table class="sticky-tasks-table">
                <caption class="sticky-table-caption">
                  Tasks passed deadline
                </caption>
                <thead>
                  <tr>
                    <th scope="col">Title</th>
                    <th scope="col">Description</th>
                    <th scope="col"></th>
                  </tr>
                </thead>
                <tbody>
                  {% for task in tasks_passed_deadline %}
                    <tr>
                      <td>{{ task.title|capfirst }}</td>
                      <td>{{ task.description|truncatechars:15 }}</td>
                      <td>
                        <a href="{% url 'tasks:view_task' task.id %}">View task
                        </a>
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            {% endif %}
          </div>
        </aside>
      </section>
    </div>
  </div>
{% endif %}
<section class="create-new-task-section">
  <div class="create-new-task-header-container">
    <h2 id="create-new-task" class="create-new-task-heading">Create New Task</h2>
  </div>
  <form
    action=""
    method="post"
    aria-labelledby="create-new-task"
    class="create-new-task-form"
  >
    {% csrf_token %}
    {% for field in form %}
      <div>
        {{ field.label_tag }}
        {{ field }}
        {% if field.help_text %}
          <span class="help-text">{{ field.help_text }}</span>
        {% endif %}
        {% if field.errors %}
          <div class="error">
            <ul>
              {% for error in field.errors %}
                <li>{{ error }}</li>
              {% endfor %}
            </ul>
          </div>
        {% endif %}
      </div>
      {% endfor %}
    <button type="submit" class="create-task-button">Create Task</button>
  </form>
</section>
{% endblock content %}

tasks/templates/view_task.html
<!-- tasks/templates/view_task.html -->
{% extends 'base.html' %}
{% load icons %}

{% block title %}View task{% endblock title %}

{% block content %}
<div class="viewing-task-header">
    <h2 class="viewing-task-heading">Viewing task {{ task.id }} | {{ task.deadline }}</h2>
    <a 
        href="{% url 'tasks:index' %}"
        class="viewing-go-back-to-tasks-link">Go back to tasks
    </a>
</div>
<section>
    <div class="message-div">
        {% if messages %}
            {% for message in messages %}
                <div class="{{ message.tags }}">
                    {{ message }}
                    <!-- Generates <i class="fa-solid fa-circle-check"></i> -->
                    {% icon 'circle-check' %}
                </div>
            {% endfor %}
        {% endif %}
    </div>
    <div class="viewing-task-container">
        <h4 id="viewing-task-title-heading">{{ task.title|capfirst }} | {% if task.priority == 1 %}
            High
            {% elif task.priority == 2 %}
            Medium
            {% else %}
            Low
            {% endif %}
            Priority
            </h4>
        <div class="viewing-task-links-div">
            <a href="{% url 'tasks:edit_task' task.id %}">Edit task</a>
            <form 
                action="{% url 'tasks:delete_task' task.id %}"
                method="POST"
                class="delete-form">
                {% csrf_token %}
                <!-- Add confirmation step -->
                <button
                    type="submit"
                    class="delete-button"
                    onclick="return confirm(
                'Are you sure you want to delete this task?'
                )">Delete task
                </button>
            </form>
        </div>
        <div class="viewing-task-category-div">
            <h5 class="viewing-task-category-heading">Category: {{ task.category }}</h5>
        </div>
        <div>
            <h6 class="viewing-task-description-heading">Description:</h6>
            <br />
            <p>{{ task.description }}</p>
        </div>
    </div>
</section>
<section class="related-tasks-section">
    <h2 class="related-tasks-heading">Related tasks</h2>
    <div class="related-tasks-container">
        <div>
            <div class="viewing-task-headings-div">
                <h4 class="viewing-task-related-heading">Deadlines</h4>
            </div>
            <div>
                {% if not tasks_with_same_deadline %}
                    <p>No tasks</p>
                {% else %}
                    {% for value in tasks_with_same_deadline %}
                        <p>
                            <span>{{ value.title|capfirst }} |</span>
                            <span>{{ value.description|truncatechars:20 }} |</span>
                            <span>
                                <a href="{% url 'tasks:view_task' value.id %}">
                                    View task
                                </a>
                            </span>
                        </p>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div>
            <div>
                <h4 class="viewing-task-related-heading">Categories</h4>
            </div>
            <div>
                {% if not tasks_with_same_category %}
                    <p>No tasks</p>
                {% else %}
                    {% for value in tasks_with_same_category %}
                        <p>
                            <span>{{ value.title|capfirst }} |</span>
                            <span>{{ value.description|truncatechars:20 }} |</span>
                            <span>
                                <a href="{% url 'tasks:view_task' value.id %}">
                                    View task
                                </a>
                            </span>
                        </p>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div>
            <div>
                <h4 class="viewing-task-related-heading">Priorities</h4>
            </div>
            <div>
                {% if not tasks_with_same_priority %}
                    <p>No tasks</p>
                {% else %}
                    {% for value in tasks_with_same_priority %}
                        <p>
                            <span>{{ value.title|capfirst }} |</span>
                            <span>{{ value.description|truncatechars:20 }} |</span>
                            <span>
                                <a href="{% url 'tasks:view_task' value.id %}">
                                    View task
                                </a>
                            </span>
                        </p>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock content %}